### ISSUE TITLE
Fix robhz786/strf issue #12

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/strf#13]
See: [Two templates for strf::range coincide](https://github.com/robhz786/strf/issues/12) - an issue of the parent repository. I need it fixed for my own work on the CUDA support feature (well, actually, for CUDA-related code that isn't part of strf for now and may not be).

**Comment by robhz786** [comment]
See my comment there

**Comment by eyalroz** [comment]
@robhz786 : Got it. Well, ok, I'll apply the change you made on your repo here as well.
