### ISSUE TITLE
Re-enable the commented-out strf code

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/strf#9]
Let's gradually enable the strf code we've commented-out, so CPU-side strf can be used as-is (or rather, for us to be able to create a PR into the main strf repository).

Input types:

* [x] float
* [x] cv_string
* [x] join
* [x] facets pack

Output types:

* [x] std::string
* [x] FILE
* [ ] std::streambuf

**Comment by robhz786** [comment]
I've recently modified  `input_types/float.hpp` in the develop branch of the original repository.
You might want to sync the changes before adapting it to CUDA

**Comment by eyalroz** [comment]
@robhz786 : Oh... I'll see what I can do.

**Comment by eyalroz** [comment]
We'll leave std::streambuf alone for now.
